services:
  ao-risk:
    build: .
    container_name: ao-risk-container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - ollama
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

volumes:
  ollama:

